development:
  adapter: sqlite3
  encoding: unicode
  database: spellbook_development
  pool: 2
production:
  adapter: sqlite3
  encoding: unicode
  pool: 5
  host: <%= ENV['DATABASE_HOST'] %>
  database: spellbook_production